export const RESET_APP = 'RESET_APP';

export const BOARDS_FETCHED = 'BOARDS_FETCHED';

export const LOGIN_DIALOG_SHOWN = 'LOGIN_DIALOG_SHOWN';
export const DIALOGS_RESET = 'DIALOGS_RESET';

export const USER_FETCHED = 'USER_FETCHED';
export const USER_AUTH_REQUESTED = 'USER_AUTH_REQUESTED';
export const USER_AUTH_SUCCEEDED = 'USER_AUTH_SUCCEEDED';
export const USER_AUTH_FAILED = 'USER_AUTH_FAILED';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const USER_RESET = 'USER_RESET';
