export const RESET_APP = 'RESET_APP';

export const BOARDS_FETCHED = 'BOARDS_FETCHED';

export const USER_AUTH_REQUESTED = 'USER_AUTH_REQUESTEDD';
export const USER_AUTH_SUCCEEDED = 'USER_AUTH_SUCCEEDED';
export const USER_AUTH_FAILED = 'USER_AUTH_FAILED';
export const USER_FETCHED = 'USER_FETCHED';
